[lazyrsync]
src.github = "westpoint-io/lazyrsync"
fetch.github = "westpoint-io/lazyrsync"

[usbtree]
src.github = "gnomeria/usbtree"
fetch.github = "gnomeria/usbtree"

[flyline]
src.github = "HalFrgrd/flyline"
fetch.github = "HalFrgrd/flyline"

[dskditto]
src.github = "jdefrancesco/dskDitto"
fetch.github = "jdefrancesco/dskDitto"

[flow]
src.github = "programmersd21/flow"
fetch.github = "programmersd21/flow"

[keyward]
src.github = "gateway-of-last-resort/keyward"
fetch.github = "gateway-of-last-resort/keyward"

[codemark]
src.github = "DanielCardonaRojas/codemark"
fetch.github = "DanielCardonaRojas/codemark"

[livediff]
src.github = "SoCkEt7/livediff"
fetch.github = "SoCkEt7/livediff"

[gotz]
src.github = "merschformann/gotz"
fetch.github = "merschformann/gotz"

[haranoaji]
src.github_tag = "trueroad/HaranoAjiFonts"
fetch.github = "trueroad/HaranoAjiFonts"

[herald]
src.github_tag = "herald-email/herald-mail-app"
fetch.github = "herald-email/herald-mail-app"

[resterm]
src.github = "unkn0wn-root/resterm"
fetch.github = "unkn0wn-root/resterm"

[astroterm]
src.github = "da-luce/astroterm"
fetch.url = "https://github.com/da-luce/astroterm/releases/download/$ver/astroterm-linux-x86_64"

[lazycut]
src.github = "emin-ozata/lazycut"
fetch.github = "emin-ozata/lazycut"

[redthread]
src.git = "https://github.com/B33pBeeps/redthread"
src.branch = "main"
fetch.git = "https://github.com/B33pBeeps/redthread"

[rura]
src.github = "tlipinski/rura"
fetch.github = "tlipinski/rura"

[omm]
src.github = "dhth/omm"
fetch.github = "dhth/omm"

[sheets]
src.github = "maaslalani/sheets"
fetch.github = "maaslalani/sheets"

[flawz]
src.github = "orhun/flawz"
fetch.github = "orhun/flawz"

[liboping]
src.github_tag = "octo/liboping"
fetch.github = "octo/liboping"

[manly]
src.github_tag = "whoop-t/manly"
fetch.github = "whoop-t/manly"

[bottom]
src.github = "ClementTsang/bottom"
fetch.github = "ClementTsang/bottom"

[hulak]
src.github = "xaaha/hulak"
fetch.github = "xaaha/hulak"

[mtr]
src.github_tag = "traviscross/mtr"
fetch.github = "traviscross/mtr"

[uuinfo]
src.github = "Racum/uuinfo"
fetch.github = "Racum/uuinfo"

[sot]
src.github = "anistark/sot"
fetch.github = "anistark/sot"

[pwdsafety]
src.github = "edoardottt/pwdsafety"
fetch.github = "edoardottt/pwdsafety"
