[lazyrsync]
src.github = "westpoint-io/lazyrsync"
fetch.github = "westpoint-io/lazyrsync"

[usbtree]
src.github = "gnomeria/usbtree"
fetch.github = "gnomeria/usbtree"

[flyline]
src.github = "HalFrgrd/flyline"
fetch.github = "HalFrgrd/flyline"

[dskditto]
src.github = "jdefrancesco/dskDitto"
fetch.github = "jdefrancesco/dskDitto"

[flow]
src.github = "programmersd21/flow"
fetch.github = "programmersd21/flow"

[keyward]
src.github = "gateway-of-last-resort/keyward"
fetch.github = "gateway-of-last-resort/keyward"

[codemark]
src.github = "DanielCardonaRojas/codemark"
fetch.github = "DanielCardonaRojas/codemark"

[livediff]
src.github = "SoCkEt7/livediff"
fetch.github = "SoCkEt7/livediff"

[gotz]
src.github = "merschformann/gotz"
fetch.github = "merschformann/gotz"
