# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dskditto = {
    pname = "dskditto";
    version = "v0.5.6";
    src = fetchFromGitHub {
      owner = "jdefrancesco";
      repo = "dskDitto";
      rev = "v0.5.6";
      fetchSubmodules = false;
      sha256 = "sha256-6p4BK6MhPhkU0NNeRIqe2KxTLtvIf43IrZ+zx11kjXk=";
    };
  };
  flow = {
    pname = "flow";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "programmersd21";
      repo = "flow";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-ZwWuFAPPHF+Q2ziXoT7yCPU6WVkAcbpnlZjXKQ/bqy0=";
    };
  };
  flyline = {
    pname = "flyline";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "HalFrgrd";
      repo = "flyline";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-KciBcUsoMCGuw8bHlVBDHAB55lDfyeGoJxBldmj0MVs=";
    };
  };
  lazyrsync = {
    pname = "lazyrsync";
    version = "v0.1.1";
    src = fetchFromGitHub {
      owner = "westpoint-io";
      repo = "lazyrsync";
      rev = "v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-JBELPmNSaiwxHq9iZHvvrCX/YLSBsOO3OrzXJ0mPrNw=";
    };
  };
  usbtree = {
    pname = "usbtree";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "gnomeria";
      repo = "usbtree";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-52Ppiv2bYLJR4/h0gyxfBtRnyCQkfNBmCNyr5hWe3uY=";
    };
  };
  whosthere = {
    pname = "whosthere";
    version = "v0.8.3";
    src = fetchFromGitHub {
      owner = "ramonvermeulen";
      repo = "whosthere";
      rev = "v0.8.3";
      fetchSubmodules = false;
      sha256 = "sha256-Q/ztOqaGONMZKQwTpwyr8/ThZxDfQVLPXHrjk1IMWsU=";
    };
  };
}
