name: "Nix Build & Cache"
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: 2gn
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: ""

      - name: Build all packages
        run: nix build -L .#packages.x86_64-linux --accept-flake-config
